// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwivg6plNEHNBTpbXLf8jsrid448Qdc6I',
    appId: '1:788816949080:web:43c47dca8e155ddf0e7f2d',
    messagingSenderId: '788816949080',
    projectId: 'webtoon-authorization',
    authDomain: 'webtoon-authorization.firebaseapp.com',
    storageBucket: 'webtoon-authorization.appspot.com',
    measurementId: 'G-YS0BVMTV61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIjfU_W0WsXrCFMZ1I39-T-bnV_gloVP0',
    appId: '1:788816949080:android:f0c7b0d086b5e5e60e7f2d',
    messagingSenderId: '788816949080',
    projectId: 'webtoon-authorization',
    storageBucket: 'webtoon-authorization.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXdhuWCpR2FendYbBTxZ_ATJP6P9aP4ps',
    appId: '1:788816949080:ios:f27941c3cb7bc2bf0e7f2d',
    messagingSenderId: '788816949080',
    projectId: 'webtoon-authorization',
    storageBucket: 'webtoon-authorization.appspot.com',
    iosClientId: '788816949080-eimmstfv8c6sb6ej88l8smv5sooc9v0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.webtoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXdhuWCpR2FendYbBTxZ_ATJP6P9aP4ps',
    appId: '1:788816949080:ios:f27941c3cb7bc2bf0e7f2d',
    messagingSenderId: '788816949080',
    projectId: 'webtoon-authorization',
    storageBucket: 'webtoon-authorization.appspot.com',
    iosClientId: '788816949080-eimmstfv8c6sb6ej88l8smv5sooc9v0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.webtoon',
  );
}
